# -*- coding: utf-8 -*-
"""Helpers for deploy.py: config generation, page compile, and Supabase sync."""
import copy
import json
import os
import re

BASE = "https://ai-rank-one.hasnainrazalakhani7272.workers.dev"
TEMPLATE_PATH = os.path.join(os.path.dirname(__file__), "course_template.html")


def generate_config():
    """Generate site/assets/js/config.js from .env so keys live in ONE place."""
    url = os.getenv("SUPABASE_URL", "https://YOUR_PROJECT.supabase.co")
    anon = os.getenv("SUPABASE_ANON_KEY", "YOUR_ANON_KEY")
    cfg = {
        "SUPABASE_URL": url,
        "SUPABASE_ANON_KEY": anon,
        "DODO_PRODUCT_SINGLE": os.getenv("DODO_PRODUCT_SINGLE", "prod_single"),
        "DODO_PRODUCT_BUNDLE": os.getenv("DODO_PRODUCT_BUNDLE", "prod_bundle"),
        "PAYMENT_READY": os.getenv("PAYMENT_READY", "false"),
        "SUBSCRIBER_COUNT_FN": url.rstrip("/") + "/functions/v1/subscriber-count",
        "AUTH_OTP_FN": url.rstrip("/") + "/functions/v1/auth-otp",
        "SUBSCRIBE_FN": url.rstrip("/") + "/functions/v1/subscribe",
    }
    body = ("// AUTO-GENERATED by scripts/deploy.py from .env — do not edit manually.\n"
            "// The Supabase anon key is public by design (protected by Row-Level Security).\n"
            "window.PUBLIC_CONFIG = " + json.dumps(cfg, ensure_ascii=False, indent=2) + ";\n")
    path = os.path.join("site", "assets", "js", "config.js")
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, "w", encoding="utf-8") as f:
        f.write(body)
    print("KEY  config.js written" + (" (PLACEHOLDERS)" if anon == "YOUR_ANON_KEY" else ""))


def summarize(slug, data):
    """Return the lightweight card record used on the home page grid."""
    return {
        "slug": slug,
        "title": data.get("title", ""),
        "description": data.get("description", ""),
        "tags": data.get("tags", []),
        "modules": len(data.get("modules", [])),
        "duration": data.get("duration", "4 hours"),
        "price": data.get("price", 39),
        "gradient": data.get("gradient", "from-brand-500 to-blue-500"),
    }


def compile_course_html(slug, data):
    """Render a static course page with gated modules stripped from public JSON."""
    public = copy.deepcopy(data)
    for idx, mod in enumerate(public.get("modules", [])):
        if idx > 0:
            mod["content"] = ""      # Clear paid content to prevent scraping.
            mod["resources"] = []    # Curated resources are paid value too.
    jsonld = json.dumps({
        "@context": "https://schema.org", "@type": "Course",
        "name": data.get("title", ""), "description": data.get("description", ""),
        "inLanguage": "ar",
        "provider": {"@type": "Organization", "name": "AI Rank One", "url": BASE + "/"},
    }, ensure_ascii=False)
    with open(TEMPLATE_PATH, encoding="utf-8") as f:
        html = f.read()
    return (html.replace("__SLUG__", slug)
                .replace("__TITLE__", data.get("title", ""))
                .replace("__DESCRIPTION__", data.get("description", ""))
                .replace("__JSONLD__", jsonld)
                .replace("__COURSE_JSON__", json.dumps(public, ensure_ascii=False)))


def inject_courses_into_index(courses_list):
    """Replace the `courses: [...]` array inside index.html's Alpine data."""
    path = os.path.join("site", "index.html")
    if not os.path.exists(path):
        return
    with open(path, encoding="utf-8") as f:
        html = f.read()
    repl = "courses: " + json.dumps(courses_list, ensure_ascii=False) + ",\n"
    html, n = re.subn(r"courses:\s*\[.*\],\s*\n", repl, html, count=1, flags=re.S)
    if n:
        with open(path, "w", encoding="utf-8") as f:
            f.write(html)
        print("PAGE injected course list into index.html")


def sync_course_to_supabase(data, slug):
    """Upsert course metadata and module contents (incl. resources) to Supabase."""
    url = os.getenv("SUPABASE_URL")
    key = os.getenv("SUPABASE_SERVICE_ROLE_KEY")
    if not url or not key or "your_" in url.lower():
        print("WARN  Supabase not configured — skipping DB sync.")
        return
    import requests
    h = {"apikey": key, "Authorization": "Bearer " + key,
         "Content-Type": "application/json", "Prefer": "resolution=merge-duplicates"}
    meta = summarize(slug, data)
    meta["modules"] = len(data.get("modules", []))
    r = requests.post(url.rstrip("/") + "/rest/v1/courses?on_conflict=slug", json=meta, headers=h)
    if r.status_code not in (200, 201):
        print("FAIL  course %s: %s %s" % (slug, r.status_code, r.text)); return
    print("OK   synced course " + slug)
    mod_url = url.rstrip("/") + "/rest/v1/course_modules?on_conflict=course_slug,module_index"
    for i, mod in enumerate(data.get("modules", [])):
        payload = {"course_slug": slug, "module_index": i, "title": mod.get("title", ""),
                   "content": mod.get("content", ""), "resources": mod.get("resources", [])}
        r = requests.post(mod_url, json=payload, headers=h)
        if r.status_code not in (200, 201):
            print("FAIL  module %s/%s: %s" % (slug, i, r.status_code))
    print("OK   synced %s modules for %s" % (len(data.get("modules", [])), slug))
